// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOGIN_PACKETTABLE_LOGINTABLE_H_
#define FLATBUFFERS_GENERATED_LOGIN_PACKETTABLE_LOGINTABLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "Utilities_generated.h"

namespace PacketTable {
namespace LoginTable {

struct VersionCheckRequest;
struct VersionCheckRequestBuilder;

struct VersionCheckResponse;
struct VersionCheckResponseBuilder;

struct SignUpRequest;
struct SignUpRequestBuilder;

struct SignUpResponse;
struct SignUpResponseBuilder;

struct LoginRequest;
struct LoginRequestBuilder;

struct LoginResponse;
struct LoginResponseBuilder;

struct VersionCheckRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VersionCheckRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4
  };
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           verifier.EndTable();
  }
};

struct VersionCheckRequestBuilder {
  typedef VersionCheckRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(VersionCheckRequest::VT_VERSION, version);
  }
  explicit VersionCheckRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VersionCheckRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VersionCheckRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VersionCheckRequest> CreateVersionCheckRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0) {
  VersionCheckRequestBuilder builder_(_fbb);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VersionCheckRequest> CreateVersionCheckRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *version = nullptr) {
  auto version__ = version ? _fbb.CreateString(version) : 0;
  return PacketTable::LoginTable::CreateVersionCheckRequest(
      _fbb,
      version__);
}

struct VersionCheckResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VersionCheckResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT = 4
  };
  int32_t result() const {
    return GetField<int32_t>(VT_RESULT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT, 4) &&
           verifier.EndTable();
  }
};

struct VersionCheckResponseBuilder {
  typedef VersionCheckResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result(int32_t result) {
    fbb_.AddElement<int32_t>(VersionCheckResponse::VT_RESULT, result, 0);
  }
  explicit VersionCheckResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VersionCheckResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VersionCheckResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VersionCheckResponse> CreateVersionCheckResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t result = 0) {
  VersionCheckResponseBuilder builder_(_fbb);
  builder_.add_result(result);
  return builder_.Finish();
}

struct SignUpRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SignUpRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCOUNT_ID = 4,
    VT_ACCOUNT_PASSWORD = 6,
    VT_NICKNAME = 8
  };
  const ::flatbuffers::String *account_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNT_ID);
  }
  const ::flatbuffers::String *account_password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNT_PASSWORD);
  }
  const ::flatbuffers::String *nickname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NICKNAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCOUNT_ID) &&
           verifier.VerifyString(account_id()) &&
           VerifyOffset(verifier, VT_ACCOUNT_PASSWORD) &&
           verifier.VerifyString(account_password()) &&
           VerifyOffset(verifier, VT_NICKNAME) &&
           verifier.VerifyString(nickname()) &&
           verifier.EndTable();
  }
};

struct SignUpRequestBuilder {
  typedef SignUpRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_account_id(::flatbuffers::Offset<::flatbuffers::String> account_id) {
    fbb_.AddOffset(SignUpRequest::VT_ACCOUNT_ID, account_id);
  }
  void add_account_password(::flatbuffers::Offset<::flatbuffers::String> account_password) {
    fbb_.AddOffset(SignUpRequest::VT_ACCOUNT_PASSWORD, account_password);
  }
  void add_nickname(::flatbuffers::Offset<::flatbuffers::String> nickname) {
    fbb_.AddOffset(SignUpRequest::VT_NICKNAME, nickname);
  }
  explicit SignUpRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SignUpRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SignUpRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SignUpRequest> CreateSignUpRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> account_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> account_password = 0,
    ::flatbuffers::Offset<::flatbuffers::String> nickname = 0) {
  SignUpRequestBuilder builder_(_fbb);
  builder_.add_nickname(nickname);
  builder_.add_account_password(account_password);
  builder_.add_account_id(account_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SignUpRequest> CreateSignUpRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *account_id = nullptr,
    const char *account_password = nullptr,
    const char *nickname = nullptr) {
  auto account_id__ = account_id ? _fbb.CreateString(account_id) : 0;
  auto account_password__ = account_password ? _fbb.CreateString(account_password) : 0;
  auto nickname__ = nickname ? _fbb.CreateString(nickname) : 0;
  return PacketTable::LoginTable::CreateSignUpRequest(
      _fbb,
      account_id__,
      account_password__,
      nickname__);
}

struct SignUpResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SignUpResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT_CODE = 4
  };
  int32_t result_code() const {
    return GetField<int32_t>(VT_RESULT_CODE, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT_CODE, 4) &&
           verifier.EndTable();
  }
};

struct SignUpResponseBuilder {
  typedef SignUpResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result_code(int32_t result_code) {
    fbb_.AddElement<int32_t>(SignUpResponse::VT_RESULT_CODE, result_code, 0);
  }
  explicit SignUpResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SignUpResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SignUpResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SignUpResponse> CreateSignUpResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t result_code = 0) {
  SignUpResponseBuilder builder_(_fbb);
  builder_.add_result_code(result_code);
  return builder_.Finish();
}

struct LoginRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCOUNT_ID = 4,
    VT_ACCOUNT_PASSWORD = 6
  };
  const ::flatbuffers::String *account_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNT_ID);
  }
  const ::flatbuffers::String *account_password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNT_PASSWORD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCOUNT_ID) &&
           verifier.VerifyString(account_id()) &&
           VerifyOffset(verifier, VT_ACCOUNT_PASSWORD) &&
           verifier.VerifyString(account_password()) &&
           verifier.EndTable();
  }
};

struct LoginRequestBuilder {
  typedef LoginRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_account_id(::flatbuffers::Offset<::flatbuffers::String> account_id) {
    fbb_.AddOffset(LoginRequest::VT_ACCOUNT_ID, account_id);
  }
  void add_account_password(::flatbuffers::Offset<::flatbuffers::String> account_password) {
    fbb_.AddOffset(LoginRequest::VT_ACCOUNT_PASSWORD, account_password);
  }
  explicit LoginRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> account_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> account_password = 0) {
  LoginRequestBuilder builder_(_fbb);
  builder_.add_account_password(account_password);
  builder_.add_account_id(account_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginRequest> CreateLoginRequestDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *account_id = nullptr,
    const char *account_password = nullptr) {
  auto account_id__ = account_id ? _fbb.CreateString(account_id) : 0;
  auto account_password__ = account_password ? _fbb.CreateString(account_password) : 0;
  return PacketTable::LoginTable::CreateLoginRequest(
      _fbb,
      account_id__,
      account_password__);
}

struct LoginResponse FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginResponseBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT_CODE = 4,
    VT_UID = 6,
    VT_NICKNAME = 8,
    VT_USER_LEVEL = 10,
    VT_PASS_LEVEL = 12,
    VT_USER_TITLE = 14,
    VT_PROFILE_SKIN = 16,
    VT_POINT = 18,
    VT_ATTENDANCE_DAY = 20,
    VT_CHARACTER_CUSTOMIZING = 22,
    VT_GOLD = 24,
    VT_DIA = 26,
    VT_MILEAGE = 28,
    VT_HAS_UNCLAIMED_REWARD = 30,
    VT_IS_NEW_UPDATE = 32
  };
  int32_t result_code() const {
    return GetField<int32_t>(VT_RESULT_CODE, 0);
  }
  int32_t uid() const {
    return GetField<int32_t>(VT_UID, 0);
  }
  const ::flatbuffers::String *nickname() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NICKNAME);
  }
  int32_t user_level() const {
    return GetField<int32_t>(VT_USER_LEVEL, 0);
  }
  int32_t pass_level() const {
    return GetField<int32_t>(VT_PASS_LEVEL, 0);
  }
  int32_t user_title() const {
    return GetField<int32_t>(VT_USER_TITLE, 0);
  }
  int32_t profile_skin() const {
    return GetField<int32_t>(VT_PROFILE_SKIN, 0);
  }
  int32_t point() const {
    return GetField<int32_t>(VT_POINT, 0);
  }
  int32_t attendance_day() const {
    return GetField<int32_t>(VT_ATTENDANCE_DAY, 0);
  }
  const PacketTable::UtilitiesTable::CharacterCustomizing *character_customizing() const {
    return GetPointer<const PacketTable::UtilitiesTable::CharacterCustomizing *>(VT_CHARACTER_CUSTOMIZING);
  }
  int32_t gold() const {
    return GetField<int32_t>(VT_GOLD, 0);
  }
  int32_t dia() const {
    return GetField<int32_t>(VT_DIA, 0);
  }
  int32_t mileage() const {
    return GetField<int32_t>(VT_MILEAGE, 0);
  }
  bool has_unclaimed_reward() const {
    return GetField<uint8_t>(VT_HAS_UNCLAIMED_REWARD, 0) != 0;
  }
  bool is_new_update() const {
    return GetField<uint8_t>(VT_IS_NEW_UPDATE, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_RESULT_CODE, 4) &&
           VerifyField<int32_t>(verifier, VT_UID, 4) &&
           VerifyOffset(verifier, VT_NICKNAME) &&
           verifier.VerifyString(nickname()) &&
           VerifyField<int32_t>(verifier, VT_USER_LEVEL, 4) &&
           VerifyField<int32_t>(verifier, VT_PASS_LEVEL, 4) &&
           VerifyField<int32_t>(verifier, VT_USER_TITLE, 4) &&
           VerifyField<int32_t>(verifier, VT_PROFILE_SKIN, 4) &&
           VerifyField<int32_t>(verifier, VT_POINT, 4) &&
           VerifyField<int32_t>(verifier, VT_ATTENDANCE_DAY, 4) &&
           VerifyOffset(verifier, VT_CHARACTER_CUSTOMIZING) &&
           verifier.VerifyTable(character_customizing()) &&
           VerifyField<int32_t>(verifier, VT_GOLD, 4) &&
           VerifyField<int32_t>(verifier, VT_DIA, 4) &&
           VerifyField<int32_t>(verifier, VT_MILEAGE, 4) &&
           VerifyField<uint8_t>(verifier, VT_HAS_UNCLAIMED_REWARD, 1) &&
           VerifyField<uint8_t>(verifier, VT_IS_NEW_UPDATE, 1) &&
           verifier.EndTable();
  }
};

struct LoginResponseBuilder {
  typedef LoginResponse Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result_code(int32_t result_code) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_RESULT_CODE, result_code, 0);
  }
  void add_uid(int32_t uid) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_UID, uid, 0);
  }
  void add_nickname(::flatbuffers::Offset<::flatbuffers::String> nickname) {
    fbb_.AddOffset(LoginResponse::VT_NICKNAME, nickname);
  }
  void add_user_level(int32_t user_level) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_USER_LEVEL, user_level, 0);
  }
  void add_pass_level(int32_t pass_level) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_PASS_LEVEL, pass_level, 0);
  }
  void add_user_title(int32_t user_title) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_USER_TITLE, user_title, 0);
  }
  void add_profile_skin(int32_t profile_skin) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_PROFILE_SKIN, profile_skin, 0);
  }
  void add_point(int32_t point) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_POINT, point, 0);
  }
  void add_attendance_day(int32_t attendance_day) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_ATTENDANCE_DAY, attendance_day, 0);
  }
  void add_character_customizing(::flatbuffers::Offset<PacketTable::UtilitiesTable::CharacterCustomizing> character_customizing) {
    fbb_.AddOffset(LoginResponse::VT_CHARACTER_CUSTOMIZING, character_customizing);
  }
  void add_gold(int32_t gold) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_GOLD, gold, 0);
  }
  void add_dia(int32_t dia) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_DIA, dia, 0);
  }
  void add_mileage(int32_t mileage) {
    fbb_.AddElement<int32_t>(LoginResponse::VT_MILEAGE, mileage, 0);
  }
  void add_has_unclaimed_reward(bool has_unclaimed_reward) {
    fbb_.AddElement<uint8_t>(LoginResponse::VT_HAS_UNCLAIMED_REWARD, static_cast<uint8_t>(has_unclaimed_reward), 0);
  }
  void add_is_new_update(bool is_new_update) {
    fbb_.AddElement<uint8_t>(LoginResponse::VT_IS_NEW_UPDATE, static_cast<uint8_t>(is_new_update), 0);
  }
  explicit LoginResponseBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginResponse>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponse(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t result_code = 0,
    int32_t uid = 0,
    ::flatbuffers::Offset<::flatbuffers::String> nickname = 0,
    int32_t user_level = 0,
    int32_t pass_level = 0,
    int32_t user_title = 0,
    int32_t profile_skin = 0,
    int32_t point = 0,
    int32_t attendance_day = 0,
    ::flatbuffers::Offset<PacketTable::UtilitiesTable::CharacterCustomizing> character_customizing = 0,
    int32_t gold = 0,
    int32_t dia = 0,
    int32_t mileage = 0,
    bool has_unclaimed_reward = false,
    bool is_new_update = false) {
  LoginResponseBuilder builder_(_fbb);
  builder_.add_mileage(mileage);
  builder_.add_dia(dia);
  builder_.add_gold(gold);
  builder_.add_character_customizing(character_customizing);
  builder_.add_attendance_day(attendance_day);
  builder_.add_point(point);
  builder_.add_profile_skin(profile_skin);
  builder_.add_user_title(user_title);
  builder_.add_pass_level(pass_level);
  builder_.add_user_level(user_level);
  builder_.add_nickname(nickname);
  builder_.add_uid(uid);
  builder_.add_result_code(result_code);
  builder_.add_is_new_update(is_new_update);
  builder_.add_has_unclaimed_reward(has_unclaimed_reward);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginResponse> CreateLoginResponseDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t result_code = 0,
    int32_t uid = 0,
    const char *nickname = nullptr,
    int32_t user_level = 0,
    int32_t pass_level = 0,
    int32_t user_title = 0,
    int32_t profile_skin = 0,
    int32_t point = 0,
    int32_t attendance_day = 0,
    ::flatbuffers::Offset<PacketTable::UtilitiesTable::CharacterCustomizing> character_customizing = 0,
    int32_t gold = 0,
    int32_t dia = 0,
    int32_t mileage = 0,
    bool has_unclaimed_reward = false,
    bool is_new_update = false) {
  auto nickname__ = nickname ? _fbb.CreateString(nickname) : 0;
  return PacketTable::LoginTable::CreateLoginResponse(
      _fbb,
      result_code,
      uid,
      nickname__,
      user_level,
      pass_level,
      user_title,
      profile_skin,
      point,
      attendance_day,
      character_customizing,
      gold,
      dia,
      mileage,
      has_unclaimed_reward,
      is_new_update);
}

}  // namespace LoginTable
}  // namespace PacketTable

#endif  // FLATBUFFERS_GENERATED_LOGIN_PACKETTABLE_LOGINTABLE_H_
