// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LoginTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LoginResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static LoginResponse GetRootAsLoginResponse(ByteBuffer _bb) { return GetRootAsLoginResponse(_bb, new LoginResponse()); }
  public static LoginResponse GetRootAsLoginResponse(ByteBuffer _bb, LoginResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ResultCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.DB_UserInfo? UserInfo { get { int o = __p.__offset(6); return o != 0 ? (PacketTable.UtilitiesTable.DB_UserInfo?)(new PacketTable.UtilitiesTable.DB_UserInfo()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int Gold { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Dia { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Mileage { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool HasUnclaimedReward { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsNewUpdate { get { int o = __p.__offset(16); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<PacketTable.LoginTable.LoginResponse> CreateLoginResponse(FlatBufferBuilder builder,
      int result_code = 0,
      Offset<PacketTable.UtilitiesTable.DB_UserInfo> user_infoOffset = default(Offset<PacketTable.UtilitiesTable.DB_UserInfo>),
      int gold = 0,
      int dia = 0,
      int mileage = 0,
      bool has_unclaimed_reward = false,
      bool is_new_update = false) {
    builder.StartTable(7);
    LoginResponse.AddMileage(builder, mileage);
    LoginResponse.AddDia(builder, dia);
    LoginResponse.AddGold(builder, gold);
    LoginResponse.AddUserInfo(builder, user_infoOffset);
    LoginResponse.AddResultCode(builder, result_code);
    LoginResponse.AddIsNewUpdate(builder, is_new_update);
    LoginResponse.AddHasUnclaimedReward(builder, has_unclaimed_reward);
    return LoginResponse.EndLoginResponse(builder);
  }

  public static void StartLoginResponse(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddResultCode(FlatBufferBuilder builder, int resultCode) { builder.AddInt(0, resultCode, 0); }
  public static void AddUserInfo(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.DB_UserInfo> userInfoOffset) { builder.AddOffset(1, userInfoOffset.Value, 0); }
  public static void AddGold(FlatBufferBuilder builder, int gold) { builder.AddInt(2, gold, 0); }
  public static void AddDia(FlatBufferBuilder builder, int dia) { builder.AddInt(3, dia, 0); }
  public static void AddMileage(FlatBufferBuilder builder, int mileage) { builder.AddInt(4, mileage, 0); }
  public static void AddHasUnclaimedReward(FlatBufferBuilder builder, bool hasUnclaimedReward) { builder.AddBool(5, hasUnclaimedReward, false); }
  public static void AddIsNewUpdate(FlatBufferBuilder builder, bool isNewUpdate) { builder.AddBool(6, isNewUpdate, false); }
  public static Offset<PacketTable.LoginTable.LoginResponse> EndLoginResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LoginTable.LoginResponse>(o);
  }
}


static public class LoginResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResultCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*UserInfo*/, PacketTable.UtilitiesTable.DB_UserInfoVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Gold*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Dia*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Mileage*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*HasUnclaimedReward*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 16 /*IsNewUpdate*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
