// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LoginTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LoginRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb) { return GetRootAsLoginRequest(_bb, new LoginRequest()); }
  public static LoginRequest GetRootAsLoginRequest(ByteBuffer _bb, LoginRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string AccountId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccountIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccountIdArray() { return __p.__vector_as_array<byte>(4); }
  public string AccountPassword { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountPasswordBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetAccountPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetAccountPasswordArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<PacketTable.LoginTable.LoginRequest> CreateLoginRequest(FlatBufferBuilder builder,
      StringOffset account_idOffset = default(StringOffset),
      StringOffset account_passwordOffset = default(StringOffset)) {
    builder.StartTable(2);
    LoginRequest.AddAccountPassword(builder, account_passwordOffset);
    LoginRequest.AddAccountId(builder, account_idOffset);
    return LoginRequest.EndLoginRequest(builder);
  }

  public static void StartLoginRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddAccountId(FlatBufferBuilder builder, StringOffset accountIdOffset) { builder.AddOffset(0, accountIdOffset.Value, 0); }
  public static void AddAccountPassword(FlatBufferBuilder builder, StringOffset accountPasswordOffset) { builder.AddOffset(1, accountPasswordOffset.Value, 0); }
  public static Offset<PacketTable.LoginTable.LoginRequest> EndLoginRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LoginTable.LoginRequest>(o);
  }
}


static public class LoginRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*AccountId*/, false)
      && verifier.VerifyString(tablePos, 6 /*AccountPassword*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
