// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LobbyTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AttendanceEventResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static AttendanceEventResponse GetRootAsAttendanceEventResponse(ByteBuffer _bb) { return GetRootAsAttendanceEventResponse(_bb, new AttendanceEventResponse()); }
  public static AttendanceEventResponse GetRootAsAttendanceEventResponse(ByteBuffer _bb, AttendanceEventResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AttendanceEventResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EventCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Result { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardCode { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardAmount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.LobbyTable.AttendanceEventResponse> CreateAttendanceEventResponse(FlatBufferBuilder builder,
      int event_code = 0,
      int result = 0,
      int reward_code = 0,
      int reward_amount = 0) {
    builder.StartTable(4);
    AttendanceEventResponse.AddRewardAmount(builder, reward_amount);
    AttendanceEventResponse.AddRewardCode(builder, reward_code);
    AttendanceEventResponse.AddResult(builder, result);
    AttendanceEventResponse.AddEventCode(builder, event_code);
    return AttendanceEventResponse.EndAttendanceEventResponse(builder);
  }

  public static void StartAttendanceEventResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEventCode(FlatBufferBuilder builder, int eventCode) { builder.AddInt(0, eventCode, 0); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(1, result, 0); }
  public static void AddRewardCode(FlatBufferBuilder builder, int rewardCode) { builder.AddInt(2, rewardCode, 0); }
  public static void AddRewardAmount(FlatBufferBuilder builder, int rewardAmount) { builder.AddInt(3, rewardAmount, 0); }
  public static Offset<PacketTable.LobbyTable.AttendanceEventResponse> EndAttendanceEventResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LobbyTable.AttendanceEventResponse>(o);
  }
}


static public class AttendanceEventResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EventCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Result*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
