// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LobbyTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AttendanceRewardRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static AttendanceRewardRequest GetRootAsAttendanceRewardRequest(ByteBuffer _bb) { return GetRootAsAttendanceRewardRequest(_bb, new AttendanceRewardRequest()); }
  public static AttendanceRewardRequest GetRootAsAttendanceRewardRequest(ByteBuffer _bb, AttendanceRewardRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AttendanceRewardRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EventCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int DayCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.LobbyTable.AttendanceRewardRequest> CreateAttendanceRewardRequest(FlatBufferBuilder builder,
      int event_code = 0,
      int day_count = 0) {
    builder.StartTable(2);
    AttendanceRewardRequest.AddDayCount(builder, day_count);
    AttendanceRewardRequest.AddEventCode(builder, event_code);
    return AttendanceRewardRequest.EndAttendanceRewardRequest(builder);
  }

  public static void StartAttendanceRewardRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddEventCode(FlatBufferBuilder builder, int eventCode) { builder.AddInt(0, eventCode, 0); }
  public static void AddDayCount(FlatBufferBuilder builder, int dayCount) { builder.AddInt(1, dayCount, 0); }
  public static Offset<PacketTable.LobbyTable.AttendanceRewardRequest> EndAttendanceRewardRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LobbyTable.AttendanceRewardRequest>(o);
  }
}


static public class AttendanceRewardRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EventCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*DayCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
