// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LobbyTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventRewardRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EventRewardRequest GetRootAsEventRewardRequest(ByteBuffer _bb) { return GetRootAsEventRewardRequest(_bb, new EventRewardRequest()); }
  public static EventRewardRequest GetRootAsEventRewardRequest(ByteBuffer _bb, EventRewardRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EventRewardRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EventCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.LobbyTable.EventRewardRequest> CreateEventRewardRequest(FlatBufferBuilder builder,
      int event_code = 0) {
    builder.StartTable(1);
    EventRewardRequest.AddEventCode(builder, event_code);
    return EventRewardRequest.EndEventRewardRequest(builder);
  }

  public static void StartEventRewardRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEventCode(FlatBufferBuilder builder, int eventCode) { builder.AddInt(0, eventCode, 0); }
  public static Offset<PacketTable.LobbyTable.EventRewardRequest> EndEventRewardRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LobbyTable.EventRewardRequest>(o);
  }
}


static public class EventRewardRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EventCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
