// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LobbyTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EventRewardResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EventRewardResponse GetRootAsEventRewardResponse(ByteBuffer _bb) { return GetRootAsEventRewardResponse(_bb, new EventRewardResponse()); }
  public static EventRewardResponse GetRootAsEventRewardResponse(ByteBuffer _bb, EventRewardResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EventRewardResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int EventCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Result { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardItem { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardItemCount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.LobbyTable.EventRewardResponse> CreateEventRewardResponse(FlatBufferBuilder builder,
      int event_code = 0,
      int result = 0,
      int reward_item = 0,
      int reward_item_count = 0) {
    builder.StartTable(4);
    EventRewardResponse.AddRewardItemCount(builder, reward_item_count);
    EventRewardResponse.AddRewardItem(builder, reward_item);
    EventRewardResponse.AddResult(builder, result);
    EventRewardResponse.AddEventCode(builder, event_code);
    return EventRewardResponse.EndEventRewardResponse(builder);
  }

  public static void StartEventRewardResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddEventCode(FlatBufferBuilder builder, int eventCode) { builder.AddInt(0, eventCode, 0); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(1, result, 0); }
  public static void AddRewardItem(FlatBufferBuilder builder, int rewardItem) { builder.AddInt(2, rewardItem, 0); }
  public static void AddRewardItemCount(FlatBufferBuilder builder, int rewardItemCount) { builder.AddInt(3, rewardItemCount, 0); }
  public static Offset<PacketTable.LobbyTable.EventRewardResponse> EndEventRewardResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LobbyTable.EventRewardResponse>(o);
  }
}


static public class EventRewardResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EventCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Result*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardItem*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardItemCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
