// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.LobbyTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GachaRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GachaRequest GetRootAsGachaRequest(ByteBuffer _bb) { return GetRootAsGachaRequest(_bb, new GachaRequest()); }
  public static GachaRequest GetRootAsGachaRequest(ByteBuffer _bb, GachaRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GachaRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int RandomBoxIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.LobbyTable.GachaRequest> CreateGachaRequest(FlatBufferBuilder builder,
      int random_box_index = 0) {
    builder.StartTable(1);
    GachaRequest.AddRandomBoxIndex(builder, random_box_index);
    return GachaRequest.EndGachaRequest(builder);
  }

  public static void StartGachaRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRandomBoxIndex(FlatBufferBuilder builder, int randomBoxIndex) { builder.AddInt(0, randomBoxIndex, 0); }
  public static Offset<PacketTable.LobbyTable.GachaRequest> EndGachaRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.LobbyTable.GachaRequest>(o);
  }
}


static public class GachaRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*RandomBoxIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
