// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.UtilitiesTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterCustomizing : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static CharacterCustomizing GetRootAsCharacterCustomizing(ByteBuffer _bb) { return GetRootAsCharacterCustomizing(_bb, new CharacterCustomizing()); }
  public static CharacterCustomizing GetRootAsCharacterCustomizing(ByteBuffer _bb, CharacterCustomizing obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterCustomizing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Skin { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Head { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Face { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Back { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.UtilitiesTable.CharacterCustomizing> CreateCharacterCustomizing(FlatBufferBuilder builder,
      int skin = 0,
      int head = 0,
      int face = 0,
      int back = 0) {
    builder.StartTable(4);
    CharacterCustomizing.AddBack(builder, back);
    CharacterCustomizing.AddFace(builder, face);
    CharacterCustomizing.AddHead(builder, head);
    CharacterCustomizing.AddSkin(builder, skin);
    return CharacterCustomizing.EndCharacterCustomizing(builder);
  }

  public static void StartCharacterCustomizing(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSkin(FlatBufferBuilder builder, int skin) { builder.AddInt(0, skin, 0); }
  public static void AddHead(FlatBufferBuilder builder, int head) { builder.AddInt(1, head, 0); }
  public static void AddFace(FlatBufferBuilder builder, int face) { builder.AddInt(2, face, 0); }
  public static void AddBack(FlatBufferBuilder builder, int back) { builder.AddInt(3, back, 0); }
  public static Offset<PacketTable.UtilitiesTable.CharacterCustomizing> EndCharacterCustomizing(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.UtilitiesTable.CharacterCustomizing>(o);
  }
}


static public class CharacterCustomizingVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Skin*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Head*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Face*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Back*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
