// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.UtilitiesTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterCustomizing : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static CharacterCustomizing GetRootAsCharacterCustomizing(ByteBuffer _bb) { return GetRootAsCharacterCustomizing(_bb, new CharacterCustomizing()); }
  public static CharacterCustomizing GetRootAsCharacterCustomizing(ByteBuffer _bb, CharacterCustomizing obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterCustomizing __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketTable.UtilitiesTable.CustomizingItem? CustomizingItems(int j) { int o = __p.__offset(4); return o != 0 ? (PacketTable.UtilitiesTable.CustomizingItem?)(new PacketTable.UtilitiesTable.CustomizingItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CustomizingItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public PacketTable.UtilitiesTable.CustomizingItem? CustomizingItemsByKey(int key) { int o = __p.__offset(4); return o != 0 ? PacketTable.UtilitiesTable.CustomizingItem.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<PacketTable.UtilitiesTable.CharacterCustomizing> CreateCharacterCustomizing(FlatBufferBuilder builder,
      VectorOffset customizing_itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    CharacterCustomizing.AddCustomizingItems(builder, customizing_itemsOffset);
    return CharacterCustomizing.EndCharacterCustomizing(builder);
  }

  public static void StartCharacterCustomizing(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddCustomizingItems(FlatBufferBuilder builder, VectorOffset customizingItemsOffset) { builder.AddOffset(0, customizingItemsOffset.Value, 0); }
  public static VectorOffset CreateCustomizingItemsVector(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.CustomizingItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCustomizingItemsVectorBlock(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.CustomizingItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomizingItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<PacketTable.UtilitiesTable.CustomizingItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCustomizingItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<PacketTable.UtilitiesTable.CustomizingItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCustomizingItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PacketTable.UtilitiesTable.CharacterCustomizing> EndCharacterCustomizing(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.UtilitiesTable.CharacterCustomizing>(o);
  }
}


static public class CharacterCustomizingVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*CustomizingItems*/, PacketTable.UtilitiesTable.CustomizingItemVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
