// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.UtilitiesTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DB_UserInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static DB_UserInfo GetRootAsDB_UserInfo(ByteBuffer _bb) { return GetRootAsDB_UserInfo(_bb, new DB_UserInfo()); }
  public static DB_UserInfo GetRootAsDB_UserInfo(ByteBuffer _bb, DB_UserInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DB_UserInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Uid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Nickname { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNicknameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNicknameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNicknameArray() { return __p.__vector_as_array<byte>(6); }
  public int UserLevel { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PassLevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Point { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AttendanceDay { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.CharacterCustomizing? CharacterCustomizing { get { int o = __p.__offset(16); return o != 0 ? (PacketTable.UtilitiesTable.CharacterCustomizing?)(new PacketTable.UtilitiesTable.CharacterCustomizing()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PacketTable.UtilitiesTable.DB_UserInfo> CreateDB_UserInfo(FlatBufferBuilder builder,
      int uid = 0,
      StringOffset nicknameOffset = default(StringOffset),
      int user_level = 0,
      int pass_level = 0,
      int point = 0,
      int attendance_day = 0,
      Offset<PacketTable.UtilitiesTable.CharacterCustomizing> character_customizingOffset = default(Offset<PacketTable.UtilitiesTable.CharacterCustomizing>)) {
    builder.StartTable(7);
    DB_UserInfo.AddCharacterCustomizing(builder, character_customizingOffset);
    DB_UserInfo.AddAttendanceDay(builder, attendance_day);
    DB_UserInfo.AddPoint(builder, point);
    DB_UserInfo.AddPassLevel(builder, pass_level);
    DB_UserInfo.AddUserLevel(builder, user_level);
    DB_UserInfo.AddNickname(builder, nicknameOffset);
    DB_UserInfo.AddUid(builder, uid);
    return DB_UserInfo.EndDB_UserInfo(builder);
  }

  public static void StartDB_UserInfo(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddUid(FlatBufferBuilder builder, int uid) { builder.AddInt(0, uid, 0); }
  public static void AddNickname(FlatBufferBuilder builder, StringOffset nicknameOffset) { builder.AddOffset(1, nicknameOffset.Value, 0); }
  public static void AddUserLevel(FlatBufferBuilder builder, int userLevel) { builder.AddInt(2, userLevel, 0); }
  public static void AddPassLevel(FlatBufferBuilder builder, int passLevel) { builder.AddInt(3, passLevel, 0); }
  public static void AddPoint(FlatBufferBuilder builder, int point) { builder.AddInt(4, point, 0); }
  public static void AddAttendanceDay(FlatBufferBuilder builder, int attendanceDay) { builder.AddInt(5, attendanceDay, 0); }
  public static void AddCharacterCustomizing(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.CharacterCustomizing> characterCustomizingOffset) { builder.AddOffset(6, characterCustomizingOffset.Value, 0); }
  public static Offset<PacketTable.UtilitiesTable.DB_UserInfo> EndDB_UserInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.UtilitiesTable.DB_UserInfo>(o);
  }
}


static public class DB_UserInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Uid*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Nickname*/, false)
      && verifier.VerifyField(tablePos, 8 /*UserLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PassLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Point*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*AttendanceDay*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 16 /*CharacterCustomizing*/, PacketTable.UtilitiesTable.CharacterCustomizingVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
