// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.UtilitiesTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Utilities : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Utilities GetRootAsUtilities(ByteBuffer _bb) { return GetRootAsUtilities(_bb, new Utilities()); }
  public static Utilities GetRootAsUtilities(ByteBuffer _bb, Utilities obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyUtilities(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, UtilitiesVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Utilities __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartUtilities(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PacketTable.UtilitiesTable.Utilities> EndUtilities(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.UtilitiesTable.Utilities>(o);
  }
  public static void FinishUtilitiesBuffer(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Utilities> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedUtilitiesBuffer(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Utilities> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class UtilitiesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
