// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_UTILITY_PACKETTABLE_UTILITYTABLE_H_
#define FLATBUFFERS_GENERATED_UTILITY_PACKETTABLE_UTILITYTABLE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace PacketTable {
namespace UtilityTable {

struct HeartBeat;
struct HeartBeatBuilder;

struct HeartBeat FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef HeartBeatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SESSIONID = 4,
    VT_TIME = 6
  };
  int32_t sessionid() const {
    return GetField<int32_t>(VT_SESSIONID, 0);
  }
  int32_t time() const {
    return GetField<int32_t>(VT_TIME, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SESSIONID, 4) &&
           VerifyField<int32_t>(verifier, VT_TIME, 4) &&
           verifier.EndTable();
  }
};

struct HeartBeatBuilder {
  typedef HeartBeat Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_sessionid(int32_t sessionid) {
    fbb_.AddElement<int32_t>(HeartBeat::VT_SESSIONID, sessionid, 0);
  }
  void add_time(int32_t time) {
    fbb_.AddElement<int32_t>(HeartBeat::VT_TIME, time, 0);
  }
  explicit HeartBeatBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<HeartBeat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<HeartBeat>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<HeartBeat> CreateHeartBeat(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t sessionid = 0,
    int32_t time = 0) {
  HeartBeatBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_sessionid(sessionid);
  return builder_.Finish();
}

}  // namespace UtilityTable
}  // namespace PacketTable

#endif  // FLATBUFFERS_GENERATED_UTILITY_PACKETTABLE_UTILITYTABLE_H_
