// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.GameTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AllPlayerReady : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static AllPlayerReady GetRootAsAllPlayerReady(ByteBuffer _bb) { return GetRootAsAllPlayerReady(_bb, new AllPlayerReady()); }
  public static AllPlayerReady GetRootAsAllPlayerReady(ByteBuffer _bb, AllPlayerReady obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AllPlayerReady __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartAllPlayerReady(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PacketTable.GameTable.AllPlayerReady> EndAllPlayerReady(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.GameTable.AllPlayerReady>(o);
  }
}


static public class AllPlayerReadyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
