// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.GameTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GameStart : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GameStart GetRootAsGameStart(ByteBuffer _bb) { return GetRootAsGameStart(_bb, new GameStart()); }
  public static GameStart GetRootAsGameStart(ByteBuffer _bb, GameStart obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GameStart __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Roomid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long Time { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<PacketTable.GameTable.GameStart> CreateGameStart(FlatBufferBuilder builder,
      int roomid = 0,
      long time = 0) {
    builder.StartTable(2);
    GameStart.AddTime(builder, time);
    GameStart.AddRoomid(builder, roomid);
    return GameStart.EndGameStart(builder);
  }

  public static void StartGameStart(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddRoomid(FlatBufferBuilder builder, int roomid) { builder.AddInt(0, roomid, 0); }
  public static void AddTime(FlatBufferBuilder builder, long time) { builder.AddLong(1, time, 0); }
  public static Offset<PacketTable.GameTable.GameStart> EndGameStart(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.GameTable.GameStart>(o);
  }
}


static public class GameStartVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Roomid*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Time*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
