// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.GameTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LifeReduce : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static LifeReduce GetRootAsLifeReduce(ByteBuffer _bb) { return GetRootAsLifeReduce(_bb, new LifeReduce()); }
  public static LifeReduce GetRootAsLifeReduce(ByteBuffer _bb, LifeReduce obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LifeReduce __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Team { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Life { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.GameTable.LifeReduce> CreateLifeReduce(FlatBufferBuilder builder,
      int team = 0,
      int life = 0) {
    builder.StartTable(2);
    LifeReduce.AddLife(builder, life);
    LifeReduce.AddTeam(builder, team);
    return LifeReduce.EndLifeReduce(builder);
  }

  public static void StartLifeReduce(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTeam(FlatBufferBuilder builder, int team) { builder.AddInt(0, team, 0); }
  public static void AddLife(FlatBufferBuilder builder, int life) { builder.AddInt(1, life, 0); }
  public static Offset<PacketTable.GameTable.LifeReduce> EndLifeReduce(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.GameTable.LifeReduce>(o);
  }
}


static public class LifeReduceVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Team*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Life*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
