// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.CheatTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct GetCurrency : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GetCurrency GetRootAsGetCurrency(ByteBuffer _bb) { return GetRootAsGetCurrency(_bb, new GetCurrency()); }
  public static GetCurrency GetRootAsGetCurrency(ByteBuffer _bb, GetCurrency obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetCurrency __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ItemCode { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.CheatTable.GetCurrency> CreateGetCurrency(FlatBufferBuilder builder,
      int item_code = 0,
      int count = 0) {
    builder.StartTable(2);
    GetCurrency.AddCount(builder, count);
    GetCurrency.AddItemCode(builder, item_code);
    return GetCurrency.EndGetCurrency(builder);
  }

  public static void StartGetCurrency(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddItemCode(FlatBufferBuilder builder, int itemCode) { builder.AddInt(0, itemCode, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(1, count, 0); }
  public static Offset<PacketTable.CheatTable.GetCurrency> EndGetCurrency(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.CheatTable.GetCurrency>(o);
  }
}


static public class GetCurrencyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ItemCode*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Count*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
