// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.GameTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BombInput : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static BombInput GetRootAsBombInput(ByteBuffer _bb) { return GetRootAsBombInput(_bb, new BombInput()); }
  public static BombInput GetRootAsBombInput(ByteBuffer _bb, BombInput obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BombInput __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Bombid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Team { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.GameTable.BombInput> CreateBombInput(FlatBufferBuilder builder,
      int id = 0,
      int bombid = 0,
      int team = 0) {
    builder.StartTable(3);
    BombInput.AddTeam(builder, team);
    BombInput.AddBombid(builder, bombid);
    BombInput.AddId(builder, id);
    return BombInput.EndBombInput(builder);
  }

  public static void StartBombInput(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddBombid(FlatBufferBuilder builder, int bombid) { builder.AddInt(1, bombid, 0); }
  public static void AddTeam(FlatBufferBuilder builder, int team) { builder.AddInt(2, team, 0); }
  public static Offset<PacketTable.GameTable.BombInput> EndBombInput(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.GameTable.BombInput>(o);
  }
}


static public class BombInputVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Bombid*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Team*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
