// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.ShopTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PurchaseGoodsResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PurchaseGoodsResponse GetRootAsPurchaseGoodsResponse(ByteBuffer _bb) { return GetRootAsPurchaseGoodsResponse(_bb, new PurchaseGoodsResponse()); }
  public static PurchaseGoodsResponse GetRootAsPurchaseGoodsResponse(ByteBuffer _bb, PurchaseGoodsResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PurchaseGoodsResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GoodsIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CurrencyIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CurrencyAmount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.ShopTable.PurchaseGoodsResponse> CreatePurchaseGoodsResponse(FlatBufferBuilder builder,
      int result = 0,
      int goods_index = 0,
      int currency_index = 0,
      int currency_amount = 0) {
    builder.StartTable(4);
    PurchaseGoodsResponse.AddCurrencyAmount(builder, currency_amount);
    PurchaseGoodsResponse.AddCurrencyIndex(builder, currency_index);
    PurchaseGoodsResponse.AddGoodsIndex(builder, goods_index);
    PurchaseGoodsResponse.AddResult(builder, result);
    return PurchaseGoodsResponse.EndPurchaseGoodsResponse(builder);
  }

  public static void StartPurchaseGoodsResponse(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddGoodsIndex(FlatBufferBuilder builder, int goodsIndex) { builder.AddInt(1, goodsIndex, 0); }
  public static void AddCurrencyIndex(FlatBufferBuilder builder, int currencyIndex) { builder.AddInt(2, currencyIndex, 0); }
  public static void AddCurrencyAmount(FlatBufferBuilder builder, int currencyAmount) { builder.AddInt(3, currencyAmount, 0); }
  public static Offset<PacketTable.ShopTable.PurchaseGoodsResponse> EndPurchaseGoodsResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.ShopTable.PurchaseGoodsResponse>(o);
  }
}


static public class PurchaseGoodsResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Result*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*GoodsIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*CurrencyIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*CurrencyAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
