// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.ShopTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ShopListResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ShopListResponse GetRootAsShopListResponse(ByteBuffer _bb) { return GetRootAsShopListResponse(_bb, new ShopListResponse()); }
  public static ShopListResponse GetRootAsShopListResponse(ByteBuffer _bb, ShopListResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShopListResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.ShopTable.GoodsList? ShopList(int j) { int o = __p.__offset(6); return o != 0 ? (PacketTable.ShopTable.GoodsList?)(new PacketTable.ShopTable.GoodsList()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ShopListLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<PacketTable.ShopTable.ShopListResponse> CreateShopListResponse(FlatBufferBuilder builder,
      int result = 0,
      VectorOffset shop_listOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ShopListResponse.AddShopList(builder, shop_listOffset);
    ShopListResponse.AddResult(builder, result);
    return ShopListResponse.EndShopListResponse(builder);
  }

  public static void StartShopListResponse(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddShopList(FlatBufferBuilder builder, VectorOffset shopListOffset) { builder.AddOffset(1, shopListOffset.Value, 0); }
  public static VectorOffset CreateShopListVector(FlatBufferBuilder builder, Offset<PacketTable.ShopTable.GoodsList>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateShopListVectorBlock(FlatBufferBuilder builder, Offset<PacketTable.ShopTable.GoodsList>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateShopListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<PacketTable.ShopTable.GoodsList>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateShopListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<PacketTable.ShopTable.GoodsList>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartShopListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PacketTable.ShopTable.ShopListResponse> EndShopListResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.ShopTable.ShopListResponse>(o);
  }
}


static public class ShopListResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Result*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*ShopList*/, PacketTable.ShopTable.GoodsListVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
