// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PlayerTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerDash : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerDash GetRootAsPlayerDash(ByteBuffer _bb) { return GetRootAsPlayerDash(_bb, new PlayerDash()); }
  public static PlayerDash GetRootAsPlayerDash(ByteBuffer _bb, PlayerDash obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerDash __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketTable.PlayerTable.PlayerPos? PlayerInfo { get { int o = __p.__offset(4); return o != 0 ? (PacketTable.PlayerTable.PlayerPos?)(new PacketTable.PlayerTable.PlayerPos()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PacketTable.PlayerTable.PlayerDash> CreatePlayerDash(FlatBufferBuilder builder,
      Offset<PacketTable.PlayerTable.PlayerPos> player_infoOffset = default(Offset<PacketTable.PlayerTable.PlayerPos>)) {
    builder.StartTable(1);
    PlayerDash.AddPlayerInfo(builder, player_infoOffset);
    return PlayerDash.EndPlayerDash(builder);
  }

  public static void StartPlayerDash(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayerInfo(FlatBufferBuilder builder, Offset<PacketTable.PlayerTable.PlayerPos> playerInfoOffset) { builder.AddOffset(0, playerInfoOffset.Value, 0); }
  public static Offset<PacketTable.PlayerTable.PlayerDash> EndPlayerDash(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PlayerTable.PlayerDash>(o);
  }
}


static public class PlayerDashVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*PlayerInfo*/, PacketTable.PlayerTable.PlayerPosVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
