// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PassTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MissionCompleteResponse : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static MissionCompleteResponse GetRootAsMissionCompleteResponse(ByteBuffer _bb) { return GetRootAsMissionCompleteResponse(_bb, new MissionCompleteResponse()); }
  public static MissionCompleteResponse GetRootAsMissionCompleteResponse(ByteBuffer _bb, MissionCompleteResponse obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MissionCompleteResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Result { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PassIndex { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MissionIndex { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PassLevel { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PassExp { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardItemIndex { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int RewardItemAmount { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.PassTable.MissionCompleteResponse> CreateMissionCompleteResponse(FlatBufferBuilder builder,
      int result = 0,
      int pass_index = 0,
      int mission_index = 0,
      int pass_level = 0,
      int pass_exp = 0,
      int reward_item_index = 0,
      int reward_item_amount = 0) {
    builder.StartTable(7);
    MissionCompleteResponse.AddRewardItemAmount(builder, reward_item_amount);
    MissionCompleteResponse.AddRewardItemIndex(builder, reward_item_index);
    MissionCompleteResponse.AddPassExp(builder, pass_exp);
    MissionCompleteResponse.AddPassLevel(builder, pass_level);
    MissionCompleteResponse.AddMissionIndex(builder, mission_index);
    MissionCompleteResponse.AddPassIndex(builder, pass_index);
    MissionCompleteResponse.AddResult(builder, result);
    return MissionCompleteResponse.EndMissionCompleteResponse(builder);
  }

  public static void StartMissionCompleteResponse(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddResult(FlatBufferBuilder builder, int result) { builder.AddInt(0, result, 0); }
  public static void AddPassIndex(FlatBufferBuilder builder, int passIndex) { builder.AddInt(1, passIndex, 0); }
  public static void AddMissionIndex(FlatBufferBuilder builder, int missionIndex) { builder.AddInt(2, missionIndex, 0); }
  public static void AddPassLevel(FlatBufferBuilder builder, int passLevel) { builder.AddInt(3, passLevel, 0); }
  public static void AddPassExp(FlatBufferBuilder builder, int passExp) { builder.AddInt(4, passExp, 0); }
  public static void AddRewardItemIndex(FlatBufferBuilder builder, int rewardItemIndex) { builder.AddInt(5, rewardItemIndex, 0); }
  public static void AddRewardItemAmount(FlatBufferBuilder builder, int rewardItemAmount) { builder.AddInt(6, rewardItemAmount, 0); }
  public static Offset<PacketTable.PassTable.MissionCompleteResponse> EndMissionCompleteResponse(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PassTable.MissionCompleteResponse>(o);
  }
}


static public class MissionCompleteResponseVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Result*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*PassIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*MissionIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PassLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*PassExp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*RewardItemIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*RewardItemAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
