// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PassTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UserMissionStateRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static UserMissionStateRequest GetRootAsUserMissionStateRequest(ByteBuffer _bb) { return GetRootAsUserMissionStateRequest(_bb, new UserMissionStateRequest()); }
  public static UserMissionStateRequest GetRootAsUserMissionStateRequest(ByteBuffer _bb, UserMissionStateRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserMissionStateRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartUserMissionStateRequest(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<PacketTable.PassTable.UserMissionStateRequest> EndUserMissionStateRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PassTable.UserMissionStateRequest>(o);
  }
}


static public class UserMissionStateRequestVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
