// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PassTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UserPassRewardState : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static UserPassRewardState GetRootAsUserPassRewardState(ByteBuffer _bb) { return GetRootAsUserPassRewardState(_bb, new UserPassRewardState()); }
  public static UserPassRewardState GetRootAsUserPassRewardState(ByteBuffer _bb, UserPassRewardState obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public UserPassRewardState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int PassType { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Level { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool IsRewarded { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<PacketTable.PassTable.UserPassRewardState> CreateUserPassRewardState(FlatBufferBuilder builder,
      int pass_type = 0,
      int level = 0,
      bool is_rewarded = false) {
    builder.StartTable(3);
    UserPassRewardState.AddLevel(builder, level);
    UserPassRewardState.AddPassType(builder, pass_type);
    UserPassRewardState.AddIsRewarded(builder, is_rewarded);
    return UserPassRewardState.EndUserPassRewardState(builder);
  }

  public static void StartUserPassRewardState(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddPassType(FlatBufferBuilder builder, int passType) { builder.AddInt(0, passType, 0); }
  public static void AddLevel(FlatBufferBuilder builder, int level) { builder.AddInt(1, level, 0); }
  public static void AddIsRewarded(FlatBufferBuilder builder, bool isRewarded) { builder.AddBool(2, isRewarded, false); }
  public static Offset<PacketTable.PassTable.UserPassRewardState> EndUserPassRewardState(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PassTable.UserPassRewardState>(o);
  }
}


static public class UserPassRewardStateVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PassType*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Level*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*IsRewarded*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
