#pragma once

enum ePacketType
{
    // Server -> Client
    S2C_HEARTBEAT,
    S2C_PLAYERADD,
    S2C_GAMEINFO,
    S2C_PLAYERMOVE,
    S2C_PLAYERSTOP,
    S2C_PLAYERPOSSYNC,
    S2C_PLAYERGRABBOMB,
    S2C_PLAYERTHROWBOMB,
    S2C_PLAYERRESPAWN,

    S2C_BLOCKDROP,
    S2C_BOMBSPAWN,
    S2C_BOMBEXPLOSION,
    S2C_BOMBPOSSYNC,
    S2C_GAMESTART,
    S2C_GAMEEND,

    S2C_LIFEREDUCE,
    S2C_REMAINTIMESYNC,

    // Client -> Server
    C2S_HEARTBEAT,
    C2S_PLAYERMOVE,
    C2S_PLAYERSTOP,
    C2S_PLAYERPOSSYNC,
    C2S_PLAYERGRABBOMB,
    C2S_PLAYERTHROWBOMB,

    C2S_BOMBINPUT,
    C2S_BOMBPOSSYNC,
    C2S_BOMBEXPLOSION

};