#pragma once

enum ePacketType
{
    // Server -> Client
    S2C_HEART_BEAT,
    S2C_PLAYER_ADD,
    S2C_PLAYER_DELETE,
    S2C_PLAYER_MOVE,
    S2C_PLAYER_STOP,
    S2C_PLAYER_SYNC,
    S2C_PLAYER_GRAB_BOMB,
    S2C_PLAYER_THROW_BOMB,
    S2C_PLAYER_GRAB_WEAPON,
    S2C_PLAYER_DROP_WEAPON,
    S2C_PLAYER_ANIMATION,
    S2C_PLAYER_DAMAGE_RECEIVE,
    S2C_PLAYER_CALCULATED_DAMAGE,
    S2C_PLAYER_DEAD,
    S2C_PLAYER_RESPAWN,
    S2C_PLAYER_GROGGY,
    S2C_PLAYER_GROGGY_RECOVERY,

    S2C_BLOCK_DROP,
    S2C_BOMB_SPAWN,
    S2C_BOMB_EXPLOSION,
    S2C_BOMB_POS_SYNC,
    S2C_WEAPON_SPAWN,
    S2C_WEAPON_DELETE,

    S2C_MATCHING_RESPONSE,
    S2C_MATCHING_CANCEL,
    S2C_ALL_PLAYER_READY,
    S2C_GAME_START,
    S2C_GAME_END,
    S2C_GAME_RESULT,
    S2C_GAME_HOST_CHANGE,

    S2C_LIFE_REDUCE,
    S2C_REMAIN_TIME_SYNC,

    // Client -> Server
    C2S_HEART_BEAT,
    C2S_PLAYER_MOVE,
    C2S_PLAYER_STOP,
    C2S_PLAYER_SYNC,
    C2S_PLAYER_GRAB_BOMB,
    C2S_PLAYER_THROW_BOMB,
    C2S_PLAYER_GRAB_WEAPON,
    C2S_PLAYER_DROP_WEAPON,
    C2S_PLAYER_ANIMATION,
    C2S_PLAYER_DAMAGE_RECEIVE,
    C2S_PLAYER_COLLISION_BLOCK,

    C2S_BOMB_INPUT,
    C2S_BOMB_POS_SYNC,
    C2S_BOMB_EXPLOSION,
    C2S_WEAPON_DELETE,

    C2S_MATCHING_REQUEST,
    C2S_MATCHING_CANCEL,
    C2S_GAME_READY
};

enum GameMode {
    INVALUE_MODE = 0,
    FITH_Indiv_Battle_2 = 111,
    FITH_Indiv_Battle_3 = 112,
    FITH_Indiv_Battle_5 = 113,
    FITH_Team_Battle_4 = 121,
    FITH_Team_Battle_6 = 122
};

enum BattleResult {
    BR_Win = 1,
    BR_Lose = 2
};

enum eCharacterType {
    CT_TEST = 1000
};

enum eWeaponType
{
    WT_HAND,
    WT_FRYING_PAN = 2001,
    WT_BAT = 2002
};

enum eBlockType
{
    BT_BLOCK_2_2_2 = 3001,
    BT_BLOCK_2_2_1 = 3002,
};

enum eAttackType
{
    AT_FALLDOWN,
    AT_BASIC
};

enum UpperBodyAnimationState
{
    NONE,
    HOLD, THROW,
    ATTACK, POWERATTACK, HEADATTACK, ROLL, FLYINGKICK, WEAPONATTACK
};