// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.ObjectTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BlockDrop : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static BlockDrop GetRootAsBlockDrop(ByteBuffer _bb) { return GetRootAsBlockDrop(_bb, new BlockDrop()); }
  public static BlockDrop GetRootAsBlockDrop(ByteBuffer _bb, BlockDrop obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BlockDrop __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketTable.UtilitiesTable.Vec2i? Pos { get { int o = __p.__offset(4); return o != 0 ? (PacketTable.UtilitiesTable.Vec2i?)(new PacketTable.UtilitiesTable.Vec2i()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int Id { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.ObjectTable.BlockDrop> CreateBlockDrop(FlatBufferBuilder builder,
      Offset<PacketTable.UtilitiesTable.Vec2i> posOffset = default(Offset<PacketTable.UtilitiesTable.Vec2i>),
      int id = 0) {
    builder.StartTable(2);
    BlockDrop.AddId(builder, id);
    BlockDrop.AddPos(builder, posOffset);
    return BlockDrop.EndBlockDrop(builder);
  }

  public static void StartBlockDrop(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPos(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec2i> posOffset) { builder.AddOffset(0, posOffset.Value, 0); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(1, id, 0); }
  public static Offset<PacketTable.ObjectTable.BlockDrop> EndBlockDrop(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.ObjectTable.BlockDrop>(o);
  }
}


static public class BlockDropVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Pos*/, PacketTable.UtilitiesTable.Vec2iVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
