// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.ObjectTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ObjectDrop : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ObjectDrop GetRootAsObjectDrop(ByteBuffer _bb) { return GetRootAsObjectDrop(_bb, new ObjectDrop()); }
  public static ObjectDrop GetRootAsObjectDrop(ByteBuffer _bb, ObjectDrop obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ObjectDrop __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public PacketTable.ObjectTable.Vec2? Pos { get { int o = __p.__offset(4); return o != 0 ? (PacketTable.ObjectTable.Vec2?)(new PacketTable.ObjectTable.Vec2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int Id { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.ObjectTable.ObjectDrop> CreateObjectDrop(FlatBufferBuilder builder,
      Offset<PacketTable.ObjectTable.Vec2> posOffset = default(Offset<PacketTable.ObjectTable.Vec2>),
      int id = 0) {
    builder.StartTable(2);
    ObjectDrop.AddId(builder, id);
    ObjectDrop.AddPos(builder, posOffset);
    return ObjectDrop.EndObjectDrop(builder);
  }

  public static void StartObjectDrop(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPos(FlatBufferBuilder builder, Offset<PacketTable.ObjectTable.Vec2> posOffset) { builder.AddOffset(0, posOffset.Value, 0); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(1, id, 0); }
  public static Offset<PacketTable.ObjectTable.ObjectDrop> EndObjectDrop(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.ObjectTable.ObjectDrop>(o);
  }
}


static public class ObjectDropVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Pos*/, PacketTable.ObjectTable.Vec2Verify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
