// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PlayerTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerThrowBomb : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerThrowBomb GetRootAsPlayerThrowBomb(ByteBuffer _bb) { return GetRootAsPlayerThrowBomb(_bb, new PlayerThrowBomb()); }
  public static PlayerThrowBomb GetRootAsPlayerThrowBomb(ByteBuffer _bb, PlayerThrowBomb obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerThrowBomb __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.PlayerTable.Vec3? Pos { get { int o = __p.__offset(6); return o != 0 ? (PacketTable.PlayerTable.Vec3?)(new PacketTable.PlayerTable.Vec3()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PacketTable.PlayerTable.Vec3? Direction { get { int o = __p.__offset(8); return o != 0 ? (PacketTable.PlayerTable.Vec3?)(new PacketTable.PlayerTable.Vec3()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int BombId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.PlayerTable.PlayerThrowBomb> CreatePlayerThrowBomb(FlatBufferBuilder builder,
      int id = 0,
      Offset<PacketTable.PlayerTable.Vec3> posOffset = default(Offset<PacketTable.PlayerTable.Vec3>),
      Offset<PacketTable.PlayerTable.Vec3> directionOffset = default(Offset<PacketTable.PlayerTable.Vec3>),
      int bomb_id = 0) {
    builder.StartTable(4);
    PlayerThrowBomb.AddBombId(builder, bomb_id);
    PlayerThrowBomb.AddDirection(builder, directionOffset);
    PlayerThrowBomb.AddPos(builder, posOffset);
    PlayerThrowBomb.AddId(builder, id);
    return PlayerThrowBomb.EndPlayerThrowBomb(builder);
  }

  public static void StartPlayerThrowBomb(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<PacketTable.PlayerTable.Vec3> posOffset) { builder.AddOffset(1, posOffset.Value, 0); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<PacketTable.PlayerTable.Vec3> directionOffset) { builder.AddOffset(2, directionOffset.Value, 0); }
  public static void AddBombId(FlatBufferBuilder builder, int bombId) { builder.AddInt(3, bombId, 0); }
  public static Offset<PacketTable.PlayerTable.PlayerThrowBomb> EndPlayerThrowBomb(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PlayerTable.PlayerThrowBomb>(o);
  }
}


static public class PlayerThrowBombVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Pos*/, PacketTable.PlayerTable.Vec3Verify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Direction*/, PacketTable.PlayerTable.Vec3Verify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*BombId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
