// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PlayerTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerGrabOtherPlayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerGrabOtherPlayer GetRootAsPlayerGrabOtherPlayer(ByteBuffer _bb) { return GetRootAsPlayerGrabOtherPlayer(_bb, new PlayerGrabOtherPlayer()); }
  public static PlayerGrabOtherPlayer GetRootAsPlayerGrabOtherPlayer(ByteBuffer _bb, PlayerGrabOtherPlayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerGrabOtherPlayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.Vec3f? Pos { get { int o = __p.__offset(6); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PacketTable.UtilitiesTable.Vec3f? Direction { get { int o = __p.__offset(8); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int TargetId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.Vec3f? TargetPos { get { int o = __p.__offset(12); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PacketTable.UtilitiesTable.Vec3f? TargetDirection { get { int o = __p.__offset(14); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PacketTable.PlayerTable.PlayerGrabOtherPlayer> CreatePlayerGrabOtherPlayer(FlatBufferBuilder builder,
      int id = 0,
      Offset<PacketTable.UtilitiesTable.Vec3f> posOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      Offset<PacketTable.UtilitiesTable.Vec3f> directionOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      int target_id = 0,
      Offset<PacketTable.UtilitiesTable.Vec3f> target_posOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      Offset<PacketTable.UtilitiesTable.Vec3f> target_directionOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>)) {
    builder.StartTable(6);
    PlayerGrabOtherPlayer.AddTargetDirection(builder, target_directionOffset);
    PlayerGrabOtherPlayer.AddTargetPos(builder, target_posOffset);
    PlayerGrabOtherPlayer.AddTargetId(builder, target_id);
    PlayerGrabOtherPlayer.AddDirection(builder, directionOffset);
    PlayerGrabOtherPlayer.AddPos(builder, posOffset);
    PlayerGrabOtherPlayer.AddId(builder, id);
    return PlayerGrabOtherPlayer.EndPlayerGrabOtherPlayer(builder);
  }

  public static void StartPlayerGrabOtherPlayer(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> posOffset) { builder.AddOffset(1, posOffset.Value, 0); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> directionOffset) { builder.AddOffset(2, directionOffset.Value, 0); }
  public static void AddTargetId(FlatBufferBuilder builder, int targetId) { builder.AddInt(3, targetId, 0); }
  public static void AddTargetPos(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> targetPosOffset) { builder.AddOffset(4, targetPosOffset.Value, 0); }
  public static void AddTargetDirection(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> targetDirectionOffset) { builder.AddOffset(5, targetDirectionOffset.Value, 0); }
  public static Offset<PacketTable.PlayerTable.PlayerGrabOtherPlayer> EndPlayerGrabOtherPlayer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PlayerTable.PlayerGrabOtherPlayer>(o);
  }
}


static public class PlayerGrabOtherPlayerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Pos*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Direction*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*TargetId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 12 /*TargetPos*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 14 /*TargetDirection*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
