// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PlayerTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerThrowOtherPlayer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerThrowOtherPlayer GetRootAsPlayerThrowOtherPlayer(ByteBuffer _bb) { return GetRootAsPlayerThrowOtherPlayer(_bb, new PlayerThrowOtherPlayer()); }
  public static PlayerThrowOtherPlayer GetRootAsPlayerThrowOtherPlayer(ByteBuffer _bb, PlayerThrowOtherPlayer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerThrowOtherPlayer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.Vec3f? Pos { get { int o = __p.__offset(6); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PacketTable.UtilitiesTable.Vec3f? Direction { get { int o = __p.__offset(8); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int OtherPlayerId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public PacketTable.UtilitiesTable.Vec3f? OtherPlayerPos { get { int o = __p.__offset(12); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public PacketTable.UtilitiesTable.Vec3f? OtherPlayerDirection { get { int o = __p.__offset(14); return o != 0 ? (PacketTable.UtilitiesTable.Vec3f?)(new PacketTable.UtilitiesTable.Vec3f()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<PacketTable.PlayerTable.PlayerThrowOtherPlayer> CreatePlayerThrowOtherPlayer(FlatBufferBuilder builder,
      int id = 0,
      Offset<PacketTable.UtilitiesTable.Vec3f> posOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      Offset<PacketTable.UtilitiesTable.Vec3f> directionOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      int other_player_id = 0,
      Offset<PacketTable.UtilitiesTable.Vec3f> other_player_posOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>),
      Offset<PacketTable.UtilitiesTable.Vec3f> other_player_directionOffset = default(Offset<PacketTable.UtilitiesTable.Vec3f>)) {
    builder.StartTable(6);
    PlayerThrowOtherPlayer.AddOtherPlayerDirection(builder, other_player_directionOffset);
    PlayerThrowOtherPlayer.AddOtherPlayerPos(builder, other_player_posOffset);
    PlayerThrowOtherPlayer.AddOtherPlayerId(builder, other_player_id);
    PlayerThrowOtherPlayer.AddDirection(builder, directionOffset);
    PlayerThrowOtherPlayer.AddPos(builder, posOffset);
    PlayerThrowOtherPlayer.AddId(builder, id);
    return PlayerThrowOtherPlayer.EndPlayerThrowOtherPlayer(builder);
  }

  public static void StartPlayerThrowOtherPlayer(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static void AddPos(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> posOffset) { builder.AddOffset(1, posOffset.Value, 0); }
  public static void AddDirection(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> directionOffset) { builder.AddOffset(2, directionOffset.Value, 0); }
  public static void AddOtherPlayerId(FlatBufferBuilder builder, int otherPlayerId) { builder.AddInt(3, otherPlayerId, 0); }
  public static void AddOtherPlayerPos(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> otherPlayerPosOffset) { builder.AddOffset(4, otherPlayerPosOffset.Value, 0); }
  public static void AddOtherPlayerDirection(FlatBufferBuilder builder, Offset<PacketTable.UtilitiesTable.Vec3f> otherPlayerDirectionOffset) { builder.AddOffset(5, otherPlayerDirectionOffset.Value, 0); }
  public static Offset<PacketTable.PlayerTable.PlayerThrowOtherPlayer> EndPlayerThrowOtherPlayer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PlayerTable.PlayerThrowOtherPlayer>(o);
  }
}


static public class PlayerThrowOtherPlayerVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Pos*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Direction*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*OtherPlayerId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTable(tablePos, 12 /*OtherPlayerPos*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 14 /*OtherPlayerDirection*/, PacketTable.UtilitiesTable.Vec3fVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
