// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketTable.PlayerTable
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PlayerGameInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PlayerGameInfo GetRootAsPlayerGameInfo(ByteBuffer _bb) { return GetRootAsPlayerGameInfo(_bb, new PlayerGameInfo()); }
  public static PlayerGameInfo GetRootAsPlayerGameInfo(ByteBuffer _bb, PlayerGameInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PlayerGameInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Ingameid { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Roomid { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<PacketTable.PlayerTable.PlayerGameInfo> CreatePlayerGameInfo(FlatBufferBuilder builder,
      int ingameid = 0,
      int roomid = 0) {
    builder.StartTable(2);
    PlayerGameInfo.AddRoomid(builder, roomid);
    PlayerGameInfo.AddIngameid(builder, ingameid);
    return PlayerGameInfo.EndPlayerGameInfo(builder);
  }

  public static void StartPlayerGameInfo(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIngameid(FlatBufferBuilder builder, int ingameid) { builder.AddInt(0, ingameid, 0); }
  public static void AddRoomid(FlatBufferBuilder builder, int roomid) { builder.AddInt(1, roomid, 0); }
  public static Offset<PacketTable.PlayerTable.PlayerGameInfo> EndPlayerGameInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<PacketTable.PlayerTable.PlayerGameInfo>(o);
  }
}


static public class PlayerGameInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Ingameid*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Roomid*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
